# apiVersion: v1
# kind: Namespace
# metadata:
#   name: tekton-devsecops
# ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-devsecops-sa
  namespace: tekton-devsecops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-devsecops-admin
subjects:
- kind: ServiceAccount
  name: tekton-devsecops-sa
  namespace: tekton-devsecops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-workspace
  namespace: tekton-devsecops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# ------------------------
# Secrets (EDIT VALUES)
# ------------------------
apiVersion: v1
kind: Secret
metadata:
  name: sonar-secret
  namespace: tekton-devsecops
type: Opaque
stringData:
  token: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-secret
  namespace: tekton-devsecops
type: Opaque
stringData:
  url: http://defectdojo:8080
  token: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
  namespace: tekton-devsecops
type: Opaque
stringData:
  webhook: CHANGE_ME
---
# ------------------------
# TASK: Git Clone
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-devsecops
spec:
  params:
  - name: repo-url
  workspaces:
  - name: output
  steps:
  - name: clone
    image: alpine/git
    script: |
      git clone $(params.repo-url) $(workspaces.output.path)
---
# ------------------------
# TASK: Maven Build
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-build
  namespace: tekton-devsecops
spec:
  workspaces:
  - name: source
  steps:
  - name: build
    image: maven:3.9-eclipse-temurin-17
    workingDir: $(workspaces.source.path)
    script: |
      mvn clean package -DskipTests
---
# ------------------------
# TASK: Unit Tests
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: unit-tests
  namespace: tekton-devsecops
spec:
  workspaces:
  - name: source
  steps:
  - name: tests
    image: maven:3.9
    workingDir: $(workspaces.source.path)
    script: |
      mvn test
---
# ------------------------
# TASK: SonarQube SAST
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sonarqube-scan
  namespace: tekton-devsecops
spec:
  # params:
  # - name: sonar-url
  workspaces:
  - name: source
  steps:
  - name: scan
    image: sonarsource/sonar-scanner-cli
    env:
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          name: sonar-secret
          key: token

    - name: SONAR_HOST_URL
      valueFrom:
        configMapKeyRef:
          name: devsecops-urls
          key: SONAR_URL

    workingDir: $(workspaces.source.path)
    script: |
      sonar-scanner \
      -Dsonar.projectKey=devsecops \
      -Dsonar.sources=. \
      -Dsonar.host.url=$SONAR_HOST_URL \
      -Dsonar.login=$SONAR_TOKEN
---
# ------------------------
# TASK: Dependency Check
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: dependency-check
  namespace: tekton-devsecops
spec:
  workspaces:
  - name: source
  steps:
  - name: dependency
    image: owasp/dependency-check
    script: |
      dependency-check.sh \
      --scan $(workspaces.source.path) \
      --format JSON \
      --out /workspace
---
# ------------------------
# TASK: Trivy FS
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: trivy-fs
  namespace: tekton-devsecops
spec:
  workspaces:
  - name: source
  steps:
  - name: scan
    image: aquasec/trivy
    script: |
      trivy fs --format json -o $(workspaces.source.path)/trivy-fs.json 
---
# ------------------------
# TASK: OPA Dockerfile
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: opa-scan
  namespace: tekton-devsecops
spec:
  workspaces:
  - name: source
  steps:
  - name: policy
    image: openpolicyagent/conftest
    script: |
      conftest test $(workspaces.source.path)/Dockerfile
---
# ------------------------
# TASK: Build Container (Kaniko)
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko-build
  namespace: tekton-devsecops
spec:
  params:
  - name: image
  workspaces:
  - name: source
  steps:
  - name: build
    image: gcr.io/kaniko-project/executor:latest
    args:
      - --dockerfile=$(workspaces.source.path)/Dockerfile
      - --context=$(workspaces.source.path)
      - --destination=$(params.image)
---
# ------------------------
# TASK: Trivy Image Scan
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: trivy-image
  namespace: tekton-devsecops
spec:
  params:
  - name: image
  workspaces:
  - name: source
  steps:
  - name: scan
    image: aquasec/trivy
    script: |
      trivy image --format json -o $(workspaces.source.path)/trivy-image.json $(params.image)
---
# ------------------------
# TASK: Upload Scan → DefectDojo
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: upload-defectdojo
  namespace: tekton-devsecops
spec:
  params:
  - name: scan-file
  - name: scan-type
  steps:
  - name: upload
    image: curlimages/curl
    env:
    - name: DD_URL
      valueFrom:
        configMapKeyRef:
          name: devsecops-urls
          key: DEFECTDOJO_URL

    - name: DD_TOKEN
      valueFrom:
        secretKeyRef:
          name: defectdojo-secret
          key: token
    script: |
      curl -X POST "$DD_URL/api/v2/import-scan/" \
      -H "Authorization: Token $DD_TOKEN" \
      -F "scan_type=$(params.scan-type)" \
      -F "file=@$(params.scan-file)"
---
# ------------------------
# TASK: GitOps Update
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: gitops-update
  namespace: tekton-devsecops
spec:
  params:
  - name: repo
  - name: image
  steps:
  - name: update
    image: alpine/git
    script: |
      git clone $(params.repo) repo
      cd repo
      sed -i "s|image:.*|image: $(params.image)|g" deployment.yaml
      git config user.email "hossamibraheem2014@gmail.com"
      git config user.name "0x70ssAM"
      git commit -am "Update image"
      git push
---
# ------------------------
# TASK: ArgoCD Deploy
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: argocd-sync
  namespace: tekton-devsecops
spec:
  params:
  - name: app
  steps:
  - name: deploy
    image: argoproj/argocd
    # command: ["/bin/sh","-c"]
    env:
    - name: ARGOCD_SERVER
      valueFrom:
        configMapKeyRef:
          name: devsecops-urls
          key: ARGOCD_URL    
    script: |
      argocd login $ARGOCD_SERVER --insecure
      argocd app sync $(params.app)
---
# ------------------------
# TASK: OWASP ZAP
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: zap-dast
  namespace: tekton-devsecops
spec:
  params:
  - name: target
  steps:
  - name: zap
    image: owasp/zap2docker-stable
    script: |
      zap-baseline.py -t $(params.target) -J $(workspaces.source.path)/zap.json
---
# ------------------------
# TASK: Slack Notify
# ------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: slack-notify
  namespace: tekton-devsecops
spec:
  params:
  - name: message
  steps:
  - name: slack
    image: curlimages/curl
    env:
    - name: WEBHOOK
      valueFrom:
        secretKeyRef:
          name: slack-secret
          key: webhook
    script: |
      curl -X POST -H 'Content-type: application/json' \
      --data "{\"text\":\"$(params.message)\"}" $WEBHOOK
---
# ------------------------
# PIPELINE
# ------------------------
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: devsecops-pipeline
  namespace: tekton-devsecops
spec:
  workspaces:
  - name: workspace
  params:
  - name: repo-url
  - name: image
  # - name: sonar-url
  - name: gitops-repo
  - name: zap-target
  - name: argocd-app

  tasks:

  - name: clone
    taskRef: {name: git-clone}
    params:
    - name: repo-url
      value: $(params.repo-url)
    workspaces:
    - name: output
      workspace: workspace

  - name: build
    runAfter: [clone]
    taskRef: {name: maven-build}
    workspaces:
    - name: source
      workspace: workspace

  - name: unit-tests
    runAfter: [build]
    taskRef: {name: unit-tests}
    workspaces:
    - name: source
      workspace: workspace

  # -------- PARALLEL SECURITY SCANS --------
  - name: sonar
    runAfter: [unit-tests]
    taskRef: {name: sonarqube-scan}
    # params:
    # - name: sonar-url
    #   value: $(params.sonar-url)
    workspaces:
    - name: source
      workspace: workspace

  - name: dependency
    runAfter: [unit-tests]
    taskRef: {name: dependency-check}
    workspaces:
    - name: source
      workspace: workspace

  - name: trivyfs
    runAfter: [unit-tests]
    taskRef: {name: trivy-fs}
    workspaces:
    - name: source
      workspace: workspace

  - name: opa
    runAfter: [unit-tests]
    taskRef: {name: opa-scan}
    workspaces:
    - name: source
      workspace: workspace
  # -----------------------------------------

  - name: build-image
    runAfter: [sonar,dependency,trivyfs,opa]
    taskRef: {name: kaniko-build}
    params:
    - name: image
      value: $(params.image)
    workspaces:
    - name: source
      workspace: workspace

  - name: image-scan
    runAfter: [build-image]
    taskRef: {name: trivy-image}
    params:
    - name: image
      value: $(params.image)

  - name: upload-trivy
    runAfter: [image-scan]
    taskRef: {name: upload-defectdojo}
    params:
    - name: scan-file
      value: $(workspaces.source.path)/trivy-image.json
    - name: scan-type
      value: Trivy Scan

  - name: gitops
    runAfter: [upload-trivy]
    taskRef: {name: gitops-update}
    params:
    - name: repo
      value: $(params.gitops-repo)
    - name: image
      value: $(params.image)

  - name: deploy
    runAfter: [gitops]
    taskRef: {name: argocd-sync}
    params:
    - name: app
      value: $(params.argocd-app)

  - name: zap
    runAfter: [deploy]
    taskRef: {name: zap-dast}
    params:
    - name: target
      value: $(params.zap-target)

  - name: upload-zap
    runAfter: [zap]
    taskRef: {name: upload-defectdojo}
    params:
    - name: scan-file
      value: $(workspaces.source.path)/zap.json
    - name: scan-type
      value: ZAP Scan

  finally:
  - name: notify
    taskRef: {name: slack-notify}
    params:
    - name: message
      value: "DevSecOps Tekton pipeline finished."
---
# ------------------------
# PipelineRun
# ------------------------
# apiVersion: tekton.dev/v1
# kind: PipelineRun
# metadata:
#   generateName: devsecops-run-
#   namespace: tekton-devsecops
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: devsecops-run
  namespace: tekton-devsecops
spec:
  taskRunTemplate:
    serviceAccountName: tekton-devsecops-sa
  # serviceAccountName: tekton-devsecops-sa
  pipelineRef:
    name: devsecops-pipeline
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: tekton-workspace
  params:
  - name: repo-url
    value: https://github.com/0x70ssAM/devsecops
  - name: image
    value: docker.io/user/app:latest
  # - name: sonar-url
  #   value: http://sonarqube:9000
  - name: gitops-repo
    value: https://github.com/0x70ssAM/devsecops
  - name: zap-target
    value: http://app.example.com
  - name: argocd-app
    value: devsecops-app
---
# ------------------------
# Tekton Trigger
# ------------------------
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
  namespace: tekton-devsecops
spec:
  params:
  - name: repo-url
    value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
  namespace: tekton-devsecops
spec:
  params:
  - name: repo-url
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: devsecops-triggered-
    spec:
      pipelineRef:
        name: devsecops-pipeline
      params:
      - name: repo-url
        value: $(tt.params.repo-url)
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: tekton-workspace
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-devsecops
spec:
  serviceAccountName: tekton-devsecops-sa
  triggers:
  - name: github-trigger
    bindings:
    - ref: github-binding
    template:
      ref: pipeline-template