############################################
# NAMESPACE
############################################
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-lab
---
############################################
# SERVICE ACCOUNT
############################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  namespace: tekton-lab
---
############################################
# TASK: GIT CLONE
############################################
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-lab
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        cd $(workspaces.output.path)
        git clone $(params.repo-url) .
---
############################################
# TASK: MAVEN BUILD
############################################
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-build
  namespace: tekton-lab
spec:
  workspaces:
    - name: source
  steps:
    - name: build
      image: maven:3.9.5-eclipse-temurin-17
      script: |
        #!/bin/bash
        set -e
        cd $(workspaces.source.path)
        mvn clean package -DskipTests
---
############################################
# TASK: TRIVY SCAN
############################################
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: trivy-scan
  namespace: tekton-lab
spec:
  workspaces:
    - name: source
  steps:
    - name: scan
      image: aquasec/trivy:latest
      script: |
        #!/bin/sh
        trivy fs $(workspaces.source.path) --exit-code 0
---
############################################
# PIPELINE
############################################
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: devsecops-test-pipeline
  namespace: tekton-lab
spec:
  params:
    - name: repo-url
      type: string
  workspaces:
    - name: shared-workspace

  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: repo-url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build
      runAfter: [clone]
      taskRef:
        name: maven-build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: scan
      runAfter: [build]
      taskRef:
        name: trivy-scan
      workspaces:
        - name: source
          workspace: shared-workspace
---
############################################
# PIPELINE RUN
############################################
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: devsecops-test-run-
  namespace: tekton-lab
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: devsecops-test-pipeline
  params:
    - name: repo-url
      value: https://github.com/spring-projects/spring-petclinic.git
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi